language: node_js
node_js:
  - "6"

before_install:
  # Download and export yarn.
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn run test
